#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /index
  controller: App\Controller\IndexController::index

bb:
  path: /bb
  controller: App\Controller\IndexController::index